### ISSUE TITLE
跳出该错误提示，但赞不妨碍使用

### ISSUE THREAD

**Issue by ciphercy** [icaca/WclPlayerScore#1]
AddOns\WclPlayerScore-WotLK_DB2\5157.lua:4: unexpected symbol near '<eof>'
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@AddOns\WclPlayerScore-WotLK\main.lua"]:19: in function <AddOns\WclPlayerScore-WotLK\main.lua:4>
[string "@AddOns\WclPlayerScore-WotLK\main.lua"]:1105: in function <AddOns\WclPlayerScore-WotLK\main.lua:1098>

**Comment by icaca** [comment]
我看了下最后一次的发布文件，应该是5157这个服务器的数据没生成完，明天凌晨会更新，到时候再试试。
