### ISSUE TITLE
数据问题集中回复贴

### ISSUE THREAD

**Issue by icaca** [icaca/WclPlayerScore#11]
**请先核对下数据，若WCL未更新，请点击WCL个人页面右侧的UPDATE，让WCL重新计算排名。**
![image](https://user-images.githubusercontent.com/279229/202317451-8ac55bc2-1a05-46b6-a61a-f9eac6fa98d6.png)

数据一般7天内会更新。若遇到数据延迟，无数据等问题，请在此帖下回复。

请提供WCL角色ID（8位数字）
**或**
用户名-服务器即可。 已发帖的不用重复提交。
本页面右侧有取消订阅的按钮，处理完毕后可以取消订阅，避免被打扰。

列如：
/character/id/{**_xxxxxxxx_**}  大括号内的就可以

**Comment by chuck0630** [comment]
我的WCL只截取了10人团的数据（蓝色分数），并没有截取25人团的数据（橙色分数）
小水果果-诺格弗格（国服）

**Comment by icaca** [comment]
https://classic.warcraftlogs.com/character/cn/%E8%AF%BA%E6%A0%BC%E5%BC%97%E6%A0%BC/%e5%b0%8f%e6%b0%b4%e6%9e%9c%e6%9e%9c#spec=Shadow&class=Priest

全明星864 排名18788 63.4% 这两个分数与团本人数没有关系的
![image](https://user-images.githubusercontent.com/279229/202243776-abd42bec-3eb8-46dd-8296-51ab1149ac03.png)

**Comment by icaca** [comment]
右边有个update按钮，点了之后变了
![image](https://user-images.githubusercontent.com/279229/202244146-9565b212-28aa-441f-ad75-0cf646455697.png)
大概2天内会更新到插件。

**Comment by boybee0328** [comment]
从网页网站上看，我的排名、国服排名、全明星都是对的，手机公众号显示也是对的。
但是进入游戏后，我的鼠标移到角色头像：显示的和网站上的不一样了
飞丷鱼  寒冰之王
这是什么原因呢

**Comment by icaca** [comment]
> 从网页网站上看，我的排名、国服排名、全明星都是对的，手机公众号显示也是对的。 但是进入游戏后，我的鼠标移到角色头像：显示的和网站上的不一样了 飞丷鱼 寒冰之王 这是什么原因呢

排名3天左右更新

**Comment by icaca** [comment]
明早更新，世界33，亚服27，服务器2

**Comment by zjxlyyds** [comment]
大佬你好我的分数显示和WCL上不一致 能帮我解决一下吗
ID:指尖旋律-卓越
![image](https://user-images.githubusercontent.com/118748389/203082437-eb6130bf-9803-402a-9137-7793abcab433.png)
![image](https://user-images.githubusercontent.com/118748389/203082600-3d40dc4c-1827-4b3b-a403-4ef2aafc7da2.png)

**Comment by icaca** [comment]
> 大佬你好我的分数显示和WCL上不一致 能帮我解决一下吗 ID:指尖旋律-卓越 ![image](https://user-images.githubusercontent.com/118748389/203082437-eb6130bf-9803-402a-9137-7793abcab433.png) ![image](https://user-images.githubusercontent.com/118748389/203082600-3d40dc4c-1827-4b3b-a403-4ef2aafc7da2.png)

明早会更新

**Comment by zjxlyyds** [comment]
> > 大佬你好我的分数显示和WCL上不一致 能帮我解决一下吗 ID:指尖旋律-卓越 ![image](https://user-images.githubusercontent.com/118748389/203082437-eb6130bf-9803-402a-9137-7793abcab433.png) ![image](https://user-images.githubusercontent.com/118748389/203082600-3d40dc4c-1827-4b3b-a403-4ef2aafc7da2.png)
> 
> 明早会更新

大佬我上周就是这个情况哦 几天都没给我更新分数了

**Comment by icaca** [comment]
数据库里已经有了，明天打包就能看到了

**Comment by icaca** [comment]
> 

你们服太强了，这分数排在第四页，要稍微等等了。

**Comment by icaca** [comment]
明天就有了。

**Comment by Tuiizz** [comment]
苕药-龙之召唤
麻烦大佬帮我看下，上周就上传了WCL，到这周插件也无显示。

**Comment by icaca** [comment]
采集的策略修改过了。后面如果还有数据问题，再另开贴吧。

**Comment by hp8712** [comment]
![image](https://user-images.githubusercontent.com/119557134/204967141-ef36856f-75dc-4b0f-8ab9-6153848ce629.png)
![image](https://user-images.githubusercontent.com/119557134/204967496-95984043-a88f-4e2b-8e8b-a6e9db4d1838.png)
大佬解决下，24号开始就不更新分数了！

**Comment by hp8712** [comment]
服务器（比格沃斯）ID（大黯黑天）

**Comment by wrongzhang626** [comment]
1、抖音搜索里凡-霜语   2、抖音搜里凡-霜语    3、你真是大聪明-霜语      4、抖音丶里凡-霜语
总共是4个角色哦，一直都没有记录，麻烦大佬了！

**Comment by lican0905** [comment]
失洛-奥罗
谢谢，一直没有数据提取显示，别的角色都显示正常。
再次感谢。

**Comment by devided666** [comment]
seeusister-维克尼拉斯
谢谢，一直没有数据提取显示，别的角色都显示正常。
再次感谢。

**Comment by lizzyljie** [comment]
服务器 比斯巨兽-ID 软酱  
网站和手机程序上的排名已经更
但是游戏里的数据一直没有更新~(大概5天了)
拜托大佬可以帮我看看嘛~  非常感谢！

**Comment by qq932134187** [comment]
服务器 霜语 ID-Rainoz、Raiin
全明星排名每天更新，分数已经一周未更新显示！

**Comment by wowercy810** [comment]
id:牛頭阿瑞斯
服務器:(台服)伊弗斯
鼠標放角色頭像上不顯示分數,別人看也沒有,其他角色正常

**Comment by wowercy810** [comment]
id:二趾狂魔
服務器:(台服)伊弗斯
鼠標放角色頭像上不顯示分數,別人看也沒有,其他角色正常

**Comment by wowercy810** [comment]
id:包大仁
服務器:(台服)伊弗斯
鼠標放角色頭像上不顯示分數,別人看也沒有,其他角色正常

**Comment by lisc18** [comment]
> **请先核对下数据，若WCL未更新，请点击WCL个人页面右侧的UPDATE，让WCL重新计算排名。** ![image](https://user-images.githubusercontent.com/279229/202317451-8ac55bc2-1a05-46b6-a61a-f9eac6fa98d6.png)
> 
> 数据一般7天内会更新。若遇到数据延迟，无数据等问题，请在此帖下回复。
> 
> 请提供WCL角色ID（8位数字） **或** 用户名-服务器即可。 已发帖的不用重复提交。 本页面右侧有取消订阅的按钮，处理完毕后可以取消订阅，避免被打扰。
> 
> 列如： /character/id/{**_xxxxxxxx_**} 大括号内的就可以
id

**Comment by lisc18** [comment]
id:地主家的女兒
服務器:(台服)古雷曼格
世界排名和玩家百分比不更新，游戏内显示更新时间5月28日，其他角色显示都是6月6日更新

**Comment by wowercy810** [comment]
id:前部落大酋長
服務器:(台服)伊弗斯
鼠標放角色頭像上不顯示分數,別人看也沒有,其他角色正常

**Comment by wowercy810** [comment]
id:與子同袍
服務器:(台服)伊弗斯
鼠標放角色頭像上不顯示分數,別人看也沒有,其他角色正常

**Comment by wowercy810** [comment]
id:二趾狂魔
服務器:(台服)伊弗斯
鼠標放角色頭像上不顯示分數,別人看也沒有,其他角色正常
之前反馈过,好了一段时间,最近又不显示了

**Comment by wowercy810** [comment]
作者大佬还在关注不,请问啥时候可以修复反馈的问题呀
