### ISSUE TITLE
台服数据是否可以加入

### ISSUE THREAD

**Issue by diw1** [icaca/WclPlayerScore#12]
由于现在国服的情况，很多人转战台服。请问是否可以新开一个文件夹来把台服的4个服务器包含进去

**Comment by diw1** [comment]
虽然有其他dev写的 (https://github.com/acelan/WCLRanks)
但是因为有WA适配性方面的问题，
以及他的抓取方式是只抓取给定的公会和个人，普适性上面有一些不足，所以提出了这个fea request

**Comment by icaca** [comment]
这两天会加上

**Comment by icaca** [comment]
过会儿会发布下，你到时候试试，我没有台服账号。

**Comment by diw1** [comment]
没有问题，刚才看了下。一个紫色的是收录了，一个灰色的没有收录到，倒是没啥问题，打一打就有了。 非常感谢
