### ISSUE TITLE
Interface\AddOns\!BugGrabber\BugGrabber.lua:193: AddOn index must be in the range of 1 to 149 

### ISSUE THREAD

**Issue by suyunxiu** [icaca/WclPlayerScore#14]
最近2个版本更新后进游戏会报这个

**Comment by AntonidasGuan** [comment]
同出现这个问题，1.4.26及以后的版本无法使用。

**Comment by icaca** [comment]
有没有其他错误？这个报错是BugGrabber的

**Comment by icaca** [comment]
两位是什么服务器的？

**Comment by suyunxiu** [comment]
我是5区审判服务器的，回滚到v1.4.25就不报这个了
[
<img width="481" alt="微信图片_20221219134803" src="https://user-images.githubusercontent.com/35566441/208356620-52b4004b-5357-4ee2-b6f4-b3629021ca13.png">
](url)

**Comment by icaca** [comment]
应该是集合太长了

**Comment by icaca** [comment]
更新了，可以试试

**Comment by AntonidasGuan** [comment]
可以了，感谢。

**Comment by suyunxiu** [comment]
好了，大佬辛苦了
