### ISSUE TITLE
游戏内全明星分数一直没有更新，只有排名在更新，今天一看wcl网站连全明星分数都没了，游戏内排名也没了，麻烦大佬帮忙看一下，祝圣诞快乐

### ISSUE THREAD

**Issue by kkyyss123456** [icaca/WclPlayerScore#15]
角色名 扇贝海蛎子 服务器 雷霆之击 
![1671933655875](https://user-images.githubusercontent.com/121367048/209454995-f0890222-1fee-433c-9d33-2e3c37ad0f14.png)
![1671933758322](https://user-images.githubusercontent.com/121367048/209455010-5f0379a2-f046-41a4-87a6-cb64f4b2c9fe.png)
![1671933790654](https://user-images.githubusercontent.com/121367048/209455017-c4715dc8-c50c-4789-b9f8-4e9135ebfb09.png)

**Comment by icaca** [comment]
右边有个更新，你按一下。有数据之后，第二天就会更新。

**Comment by icaca** [comment]
你的名次居然是-47.7% 太奇怪了

**Comment by kkyyss123456** [comment]
@icaca 感谢大佬，今天更新后没有问题！！提前祝您新年快乐~
