### ISSUE TITLE
请问有加入欧服美服数据的计划吗

### ISSUE THREAD

**Issue by superlahm** [icaca/WclPlayerScore#17]
欧服美服有大量的国人玩家群体，也十分期待这个插件的数据库能够涵盖欧美服。请问有相关计划吗？

**Comment by icaca** [comment]
如果有服务器列表的话，可以增加一下。

**Comment by icaca** [comment]
我找到了 晚点研究下

**Comment by icaca** [comment]
已经加上了 可以试试行不行，我没有外服账号，测试不了。

**Comment by superlahm** [comment]
我在欧服，经尝试并没有效果。分别试了github和curseforge的包，插件勾选了所有数据包，也分别试了正常加载所有插件和只加载wclplayerscore插件（及数据包），姓名版都看不到分数和排名

**Comment by superlahm** [comment]
原因找到了，main.lua里：
	local ScoreDB6 = { "伊弗斯", "瑪拉頓", "阿拉希盆地", "魚人", "逐風者", "古雷曼格", "札里克", "烏蘇雷"}
需要添加新增的欧美服务器名称，我加上我的服务器名称后就好使了。

多谢大佬！！！！

**Comment by icaca** [comment]
加上了，明天再看看哦

**Comment by superlahm** [comment]
可以正常使用了，赞美大佬
