### ISSUE TITLE
发现个小问题

### ISSUE THREAD

**Issue by Dcccccccccccccccccc** [icaca/WclPlayerScore#2]
WclPlayerScore-WotLK_DB1.toc 这个的第二行和后续服务器错了 应该是## Title: WclPS-WotLK|cFF3782D1[一区数据包#1]|r  服务器应该是5039.lua
5041.lua
5142.lua
5144.lua
5114.lua
5116.lua
5117.lua
5119.lua
5136.lua
5141.lua
5145.lua
5159.lua

目前1区的这些服务器进去都看不到数据 更改后就好了

**Comment by Dcccccccccccccccccc** [comment]
等这个插件等很久了 但碍于水平不够 只能自己研究 现在只想说大佬牛逼~!!!

**Comment by icaca** [comment]
我过会儿检查下

**Comment by Dcccccccccccccccccc** [comment]
大佬 爬虫能否分享一下呢 我希望能爬一下自己服务器的数据 更新频率就可以快一点 万分感谢
