### ISSUE TITLE
作者大大 插件显示的本服务器排名已更新为TOC，但是台服排名还是ULD，同时未显示世界排名，求更新，非常感谢！

### ISSUE THREAD

**Issue by YXTGemini** [icaca/WclPlayerScore#20]
服务器：伊弗斯
角色名：成長接滋養
![image](https://github.com/icaca/WclPlayerScore/assets/139004621/451f13f2-d99c-4cb6-87ad-30e82e4e3e2f)
![image](https://github.com/icaca/WclPlayerScore/assets/139004621/d173554a-e57d-495d-9c27-9bbcf0133c18)

**Comment by icaca** [comment]
["成長接滋養"]="AD:(平衡)373/99.6%AT:(平衡)19/99.9%|0",

["成長接滋養"]="2平衡德",

**Comment by YXTGemini** [comment]
谢谢大佬 台服排名显示还是ULD的40名 未显示TOC世界排名19  我等明天插件更新再看一下

**Comment by icaca** [comment]
更新后世界排名统一使用TOC的数据

**Comment by YXTGemini** [comment]
感谢大佬 排名已正常显示
