### ISSUE TITLE
美服目前的全明星分数都还是TOC的没更新到ICC

### ISSUE THREAD

**Issue by williamwmm** [icaca/WclPlayerScore#26]
![1234](https://github.com/icaca/WclPlayerScore/assets/35707408/ce3e67b1-f1a3-428f-837e-5b281d9b995a)

如题，目前美服的全明星分数应该都还是TOC的，随便在达拉然截图就能看出来问题。

**Comment by icaca** [comment]
Sudakki 11月3日更新
Grymx 11月6日更新
排名按照25HICC

**Comment by williamwmm** [comment]
收到，全明星确实修好了。。但是游戏内显示变成ULD/TOC了。。。
还是随意截两张图。
![222](https://github.com/icaca/WclPlayerScore/assets/35707408/52084e5a-f150-4ef3-bd5e-2b72dd326750)
![22222](https://github.com/icaca/WclPlayerScore/assets/35707408/a63c103b-8714-4833-9656-5001ce47f107)

**Comment by icaca** [comment]
改好了
