### ISSUE TITLE
显示格式上可否改回原来区分天赋的形式呢

### ISSUE THREAD

**Issue by fengyuchuan** [icaca/WclPlayerScore#3]
目前这种只有积分和百分比排名的情况，不太能够明确详细的天赋打出来的积分，可否改成区分天赋呢，在爬取的时候针对天赋分别计算积分

**Comment by icaca** [comment]
有没有截图可以参考下

**Comment by fengyuchuan** [comment]
![微信图片_20221103183418](https://user-images.githubusercontent.com/24790249/199699687-3c288c4f-17aa-42ff-8104-be204bf0728e.jpg)
找到了工会成员保存的一张截图，他的全明星积分上会标记出是按照什么天赋打出的积分，应该是按照了不同的天赋去分别获取的积分

**Comment by icaca** [comment]
全明星上是有天赋的，这个用的是哪个版本的，我去抄抄代码。

**Comment by icaca** [comment]
[WclPlayerScore-TBC-CN](https://www.curseforge.com/wow/addons/wclplayerscore-tbc-cn) 这个版本里有天赋的，我研究下怎么合并

**Comment by fengyuchuan** [comment]
是的，TBC阶段用的是这个版本，https://cn.classic.warcraftlogs.com/character/id/66150244#spec=Protection&class=Paladin，看起来像是获取的时候通过spec获取的专精，然后按照 职业/专精 两个维度进行同时排名的

**Comment by icaca** [comment]
[发布好了](https://github.com/icaca/WclPlayerScore/releases/tag/v1.1.2)

**Comment by fengyuchuan** [comment]
目前发现一个小的优化点，TBC版本的插件，如果一个职业多个天赋都进排行榜了，它是会同时提示的，如上图，但是现在好像只会显示一系天赋，这个可以优化下吗

**Comment by icaca** [comment]
现在已经是这样了
只不过世界、国服、服务器，各显示一个，譬如说国服排名2个天赋都进了，只显示靠前的那个。

**Comment by fengyuchuan** [comment]
原有的版本的逻辑是多个天赋都会显示，因为部分DPS职业可能会多天赋冲榜，这种情况的话，后期会考虑增加多天赋同时显示排名吗

**Comment by icaca** [comment]
首先最早的版本只显示世界排名
wlk版本只显示国服排名
我研究过之前的代码，好像没看到你说的那部分
如果有例子可以发个截图。

**Comment by icaca** [comment]
下周抽空弄弄

**Comment by icaca** [comment]
应该可以了
