### ISSUE TITLE
分数很久没更新 一直是12.24

### ISSUE THREAD

**Issue by bnerDY** [icaca/WclPlayerScore#32]
分数很久没更新 一直是12.24
![image](https://github.com/icaca/WclPlayerScore/assets/5085327/00b6133d-19f3-4eb1-b7fc-08e9f0ce3ea3)

**Comment by icaca** [comment]
服务器？角色名？

**Comment by bnerDY** [comment]
服务器 阿拉希盆地，Ucat @icaca

**Comment by icaca** [comment]
今早的数据已经有了

**Comment by bnerDY** [comment]
> 今早的数据已经有了

好的，谢谢，我看最新更新时间是1-9。但是我的数据可能是10号更新的，麻烦看下谢谢！
