### ISSUE TITLE
游戏内不显示WCL分数

### ISSUE THREAD

**Issue by Leonlooo** [icaca/WclPlayerScore#33]
<img width="768" alt="寒宇良" src="https://github.com/icaca/WclPlayerScore/assets/153085869/8529842f-cb00-4b7f-93d5-65309cffc525">
<img width="767" alt="太宰治" src="https://github.com/icaca/WclPlayerScore/assets/153085869/8f5aa9a9-6b1e-4824-9bf9-794a6a69ce16">
，
请问下大佬
我的两个号 ： 寒宇良-
逐風者 (台服)；太宰治-逐風者 (台服)  为什么一直没有分数，我每天都用curse更新插件，也删除过缓存，一直不显示WCL分数，看别人是正常的，麻烦大佬帮忙看看或者手动更新下，谢谢。

**Comment by icaca** [comment]
程序修改好了，数据需要跑2天，等两天看看。

**Comment by Leonlooo** [comment]
谢谢大佬抽空处理，辛苦了！
