### ISSUE TITLE
大佬新年快乐！游戏内排名信息不更新等情况，帮忙看看，谢谢

### ISSUE THREAD

**Issue by LeonXU2024** [icaca/WclPlayerScore#34]
一个是古雷德曼的号，名字笑笑生，应该已经服4，但有三周左右没更新了。
还有个是伊芙斯的号，名字墨森，也是同一个情况，持续有个把月了。
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=4388694585221044301 skey=@crypt_772fa6d1_e7e026fe493bf82739682cabed0b6d66 mmweb_appid=wx_webfilehelper (1)](https://github.com/icaca/WclPlayerScore/assets/155517310/2e39ec0e-870d-42d7-b9d1-9ca08797b9ed)
![2024-01-03 古雷德曼-笑笑生](https://github.com/icaca/WclPlayerScore/assets/155517310/273d9947-d62a-42d2-b3b1-5ff465c7c08b)
![2024-01-03 伊芙斯-墨森](https://github.com/icaca/WclPlayerScore/assets/155517310/7461c18f-d070-4f20-b2c3-cab4854602cf)

**Comment by icaca** [comment]
查了下，排名数据的确有问题，明早更新下
