### ISSUE TITLE
大佬我的WCL游戏内也不显示

### ISSUE THREAD

**Issue by Tanke1235** [icaca/WclPlayerScore#35]
每天都更新WCL插件不知道什么原因就是不显示这个号的,其他角色都能正常显示 看别人的分数也能正常显示 
就是自己的不显示  
麻烦看看是怎么回事
[逐風者 (台服)]
离离原上草丶
![QQ截图20240103235052](https://github.com/icaca/WclPlayerScore/assets/155563225/3ed2c460-f39c-4350-8645-7ce5bf7b553f)

**Comment by icaca** [comment]
程序修改好了，数据需要跑2天，等两天看看。
