### ISSUE TITLE
数据未更新

### ISSUE THREAD

**Issue by DannyXING77** [icaca/WclPlayerScore#36]
5200里面的部分数据好像自12/24之后就没有更新，我自己的号“壹剣淩雲”是这种情况，麻烦老大看看是不是有这个问题。

**Comment by icaca** [comment]
wcl上搜不到壹剣淩雲

**Comment by DannyXING77** [comment]
寫錯了，是這個
壹劍淩雲

**Comment by icaca** [comment]
我看了 有数据的。

**Comment by DannyXING77** [comment]
是有数据，但是没更新，我看WCL网址上是有不少的提升的，但是插件里12月24之后就没变过了

**Comment by icaca** [comment]
icc 积分: 519.72 Rank: 13186 排名: 74.4%
toc 积分: 387.43  RANK: 7284 排名: 87.9%
有什么问题？
