### ISSUE TITLE
数据感觉不完整

### ISSUE THREAD

**Issue by guanke8023** [icaca/WclPlayerScore#37]
我的账号下有7个角色，现在只有一个（濫用遊戲機制-瑪拉頓）能顯示ICC分数，在WclPlayerScore-WotLK_DB6文件里也搜索过，确实也只有这个角色有数据。

不知道开发者大佬抓取数据的规则是什么样子的，有些角色以前好像有分，不知道从哪次更新后就没了。最近打团也发现，团里大部分人都是没有分数了，有些角色明明这几周都有见过也上传过WCL的。

蟹熊-瑪拉頓
維持懲處-瑪拉頓

PO两个角色名供大佬排错，感谢。

**Comment by 91po** [comment]
这两天更新RS的数据，如果下周还没有再查下。

**Comment by icaca** [comment]
最近更新rs的数据，如果明天还没有的话，麻烦再反馈下。
