### ISSUE TITLE
全明星排名

### ISSUE THREAD

**Issue by yan1891** [icaca/WclPlayerScore#38]
大佬我看新版的全明星排名是显示RS的排名 能不能改成ICC的排名？

**Comment by icaca** [comment]
的确是改成RS的排名了，为何要改为ICC呢

**Comment by yan1891** [comment]
1、RS只有一个BOSS，偶然性比较大；
2、RS有内外场之分，内场和外场DPS差距很大。
因此，相比ICC，RS不能准确的反应玩家的水平。

**Comment by yan1891** [comment]
https://ngabbs.com/read.php?tid=39253731   已发起投票 请大佬关注一下

**Comment by 88363339** [comment]
支持修改回ICC全明星分，RS的分内外场差距太大配置都不一样 感谢作者关注此事

**Comment by yan1891** [comment]
https://ngabbs.com/read.php?tid=39253731 大佬你好 投票期已经结束 大部分玩家还是希望改回icc的排名

**Comment by icaca** [comment]
👌，这两天有空就改

**Comment by icaca** [comment]
改过了

**Comment by kbwwolf** [comment]
大佬，1.19.7更新后不显示战士的分数了，其他职业都显示，麻烦有时间调整下，感谢！
