### ISSUE TITLE
世界排名、国服排名、服务器排名

### ISSUE THREAD

**Issue by ShamanProtect** [icaca/WclPlayerScore#4]
大佬您好，请问能否增加一项内容，就是服务器/国服排名呢，毕竟打个好成绩也希望给人看看嘛哈哈

**Comment by icaca** [comment]
我这两天在研究这个需求，我发现个人页面不包含服务器排名和区域排名。只有手机端有。
所以这个问题我还在研究数据到哪去取。

**Comment by icaca** [comment]
全明星上有图标，就是专精的。

**Comment by icaca** [comment]
我看以前的数据里面还有速通的排名，不知道从哪里来的

**Comment by fengyuchuan** [comment]
速通排名是指什么呢，副本的通关速度，还是指第一个打通副本的进度呢

**Comment by icaca** [comment]
老版本的top.lua
CTOP_Database = {
["小牛牛耶_范克瑞斯"] = "国服竞速第一猎人",
["Arisa_范克瑞斯"] = "国服竞速第二猎人",
["Sivir_厄运之槌"] = "国服竞速第三猎人",

**Comment by icaca** [comment]
https://www.curseforge.com/wow/addons/wclplayerscore

**Comment by icaca** [comment]
已发布 https://github.com/icaca/WclPlayerScore/tree/v1.2.3

**Comment by depraveds** [comment]
大佬想问一下，为什么没有恶魔术的排名，其他所有职业的所有专精都有，唯独术士的恶魔学识专精没有排名，只有百分比，痛苦术和毁灭术都有排名。是否是BUG，我是用恶魔术冲分的，没有排名很难受=.=
