### ISSUE TITLE
WCL分数没有刷新

### ISSUE THREAD

**Issue by DannyXING77** [icaca/WclPlayerScore#42]
麻烦大佬查看一下，
台服阿拉希
壹劍淩雲
https://cn.classic.warcraftlogs.com/character/tw/%E9%98%BF%E6%8B%89%E5%B8%8C%E7%9B%86%E5%9C%B0/%e5%a3%b9%e5%8a%8d%e6%b7%a9%e9%9b%b2#partition=5
分数之前还有，从本周开始没有了

**Comment by icaca** [comment]
应该已经有了
