### ISSUE TITLE
WCL显示不统一

### ISSUE THREAD

**Issue by adolmad** [icaca/WclPlayerScore#45]
首先感谢作者的努力与付出，非常喜欢这款插件。
最近出现了一个问题
插件在游戏内显示的分数及排名与WCL网站显示不一样，已经持续一周多了。
服务器：台服，服务器：逐风者，角色名：Madc
截图详见附件
![游戏内wcl](https://github.com/icaca/WclPlayerScore/assets/163131461/0d413144-3cf7-498f-9e07-9ccd02ef3928)
![wcl网站](https://github.com/icaca/WclPlayerScore/assets/163131461/0a3f5956-c390-448e-8631-963f9207b1d8)

**Comment by icaca** [comment]
已更新

**Comment by adolmad** [comment]
尊敬的作者你好：
请问该软件还更新吗？
目前游戏内有的角色更新到2024年4月3日，有的却是2024年4月4日
如果可能话，希望作者更新到2024年4月9日-4月10日.
感恩。
















在 2024-03-25 07:56:31，"caca" ***@***.***> 写道：

已更新
