### ISSUE TITLE
WCL榜单更新到了P4.5，请问插件也会更新P4.5的全明星排名吗？

### ISSUE THREAD

**Issue by Lemonisn** [icaca/WclPlayerScore#46]
如题，

WCL榜单更新到了P4.5，请问插件也会更新P4.5的全明星排名吗？

感谢！

**Comment by icaca** [comment]
更新什么了，晚点看下

**Comment by Lemonisn** [comment]
> 更新什么了，晚点看下

因为不能去掉春节期间年兽BUFF的影响，所以WCL网站决定新开一个P4.5的榜单，同时全明星排名也与这个新榜单挂钩。

**Comment by icaca** [comment]
默认的榜单就是最新的。有问题的话反馈角色。

**Comment by Lemonisn** [comment]
目前24号更新的版本，游戏内显示还是P4buff榜单的排名，而非最新P4.5排名。

随意截图下，
![屏幕截图 2024-03-24 231647](https://github.com/icaca/WclPlayerScore/assets/164480574/23939622-016c-4614-a4f7-89898e86fdb3)
该排名为P4buff榜排名，96名。

![屏幕截图 2024-03-24 231735](https://github.com/icaca/WclPlayerScore/assets/164480574/6d61c8d0-31cb-49b9-8bc8-414bfa626c3e)
WCL榜单已经更新至P4.5榜排名，94名。

**Comment by icaca** [comment]
我看了下 的确是多了一个阶段 明天应该能更新排名
