### ISSUE TITLE
您好 有一个关于角色分数显示有误的问题 想请您解决

### ISSUE THREAD

**Issue by AELFRICLAU** [icaca/WclPlayerScore#47]
台服古雷曼格——FS——Aelfric，官方显示为94.5，但插件始终显示为85.7，想请您解决，感谢！

**Comment by icaca** [comment]
HICC 的排名就是 85.7%

**Comment by AELFRICLAU** [comment]
![IMG_7674](https://github.com/icaca/WclPlayerScore/assets/150167670/ecb80b12-9486-4366-bd4c-a5ee90e9b995)
您好，我刚刚又确认了一下HICC的分数，PC端查询也是一样的结果。

**Comment by icaca** [comment]
![image](https://github.com/icaca/WclPlayerScore/assets/279229/007d0682-a93b-4f82-a196-d121af314ded)
