### ISSUE TITLE
请问还更新吗？

### ISSUE THREAD

**Issue by adolmad** [icaca/WclPlayerScore#49]
尊敬的作者你好：
请问该软件还更新吗？
目前游戏内有的角色更新到2024年4月1日，有的却是2024年4月4日
如果可能话，希望作者更新到2024年4月9日-4月10日.
感恩。
亚服，服务器：逐风者，角色ID：善惡
![善恶A1](https://github.com/icaca/WclPlayerScore/assets/163131461/f4b00b6b-413d-450d-a88f-c330f193ba8b)
![善恶A2](https://github.com/icaca/WclPlayerScore/assets/163131461/6c90d167-6e0d-4de2-b34b-bd3d4dab15a8)

**Comment by icaca** [comment]
项目首页有写。
