### ISSUE TITLE
爬虫数据里的“每个角色都有独立的更新时间” 是否需要调整？

### ISSUE THREAD

**Issue by CmcnPro** [icaca/WclPlayerScore#8]
因为现在WCL有评分未锁定的一个状态，当WCL锁定评分后，全明星和评分会产生变化，而爬虫采集还是之前未锁定的数据。

ID Zovaal - 寒脊山小径
日志上传时间2022/11/10 22:40
游戏内插件截图
![image](https://user-images.githubusercontent.com/11855767/201502939-3e93cf11-d172-4172-822d-f9c722995c95.png)
显示采集时间为11/11 根据README说法为早上11/11/8:00采集。
当WCL数据锁定后WCL官网显示的为
![image](https://user-images.githubusercontent.com/11855767/201503070-612fcd03-5a1e-4e57-a117-3ca34966eeb1.png)
这时无论是排名还是全明星分都和之前的爬虫数据都不一样。

**Comment by icaca** [comment]
采集时间不固定，插件打包是8点。
数据核对要点进个人页面。

**Comment by CmcnPro** [comment]
关于个人页面的全明星分
![image](https://user-images.githubusercontent.com/11855767/201503711-4f5bf51d-9c7a-4425-b9b5-6afa8d2982af.png)
[https://cn.classic.warcraftlogs.com/character/id/68314970?mode=detailed&zone=1015#metric=dps](https://cn.classic.warcraftlogs.com/character/id/68314970?mode=detailed&zone=1015#metric=dps)

关于服务器的全明星排名
以寒脊山小径 邪DK为例
![image](https://user-images.githubusercontent.com/11855767/201503985-15e4c10b-503e-4e0a-9b6a-28677f825e0b.png)

请问是否有改善爬虫数据时效性的想法吗？当然这就涉及到资源开销和反爬虫等问题了

**Comment by icaca** [comment]
你的想法不错，给了我一些启发。
我再优化下逻辑。

**Comment by icaca** [comment]
你的DK最后更新时间是2022-11-11 16:10:37
具体wcl何时会分析报告，重新统计全明星和排名，这个不太清楚。
不过每个用户都有个手动更新的功能，下次上传完，可以按了试试。

**Comment by icaca** [comment]
这个应该是个bug，把10人的排名覆盖了25人的，已经恢复了。
